version: "3.8"

services:
  backend:
    image: concord-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - backend-db:/app/database.sqlite
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    image: concord-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  backend-db:

networks:
  app-network:
    external: true