version: "3.8"

services:
  backend:
    image: concord-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - concord-db:/app/database.sqlite
    networks:
      - app-network

  frontend:
    image: concord-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: overlay  # necessário para Swarm

volumes:
  concord-db: